#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogInactive)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeftPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorRightPulley, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoNull1,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servoNull2,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_5,    servoNull3,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servoNull4,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Initializes all global variables
int _dirDC = 0;
int _dirAC = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;
int irNear = 0;
int irFar = 0;
int irDist = 0;
int irTotal = 0;
int preset = 0;
int num = 0;
int ramp = 0;
int red = 0;
int blue = 0;
int irMax = 0;
float ultsonar = 0.0;
int irTotalOld = 0;
float alignDir = 0.0;
int final = 0;
int count = 1;
char option1 = 'a';
char option2 = 'a';
char option3 = 'a';
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;

//Includes header files

//Includes ability to use joysticks(not sure if necessary)
#include "JoystickDriver.c"
//General drivers for Xander's sensors
#include "drivers\hitechnic-sensormux.h"
//Drivers for IR seeker
#include "drivers\hitechnic-irseeker-v2.h"
//Drivers for Gyro Sensor
#include "drivers\hitechnic-gyro.h"
//Reads the IR and returns a total
#include "readIR.h"
//Writes to file "test.txt"
#include "writeStats.h"
//Resets motors, encoders and doneReset
#include "reset.h"
//Allows for turns using the gyroscopic sensors
#include "gyroTurn.h"
//FloorThreeCMethods
#include "floorThreeCMethods.h"
//Moves robot
#include "moveRobot.h"
//Moves robot(with only back wheel encoders)
#include "moveRobotRearW.h"
//AUTONOMOUS CHOOSER!!!
#include "autonomousChooser.h"
//Button for debugging, stops autonomous immediately when back right bumper is pressed
#include "emergency.h"
//Drops baseball or golf ball into center goal when already aligned
#include "liftCenter.h"
//When aligned with center goal, moves robot forward into position
#include "moveSonar.h"
//In floorOneA, aligns robot with the center goal
#include "floorThreeAMethods.h"
//Calibrates and finds starting position of the center goal
#include "startPos.h"
//File for running autonomous in case of center goal in position 3
#include "presetOne.h"
//File for running autonomous in case of center goal in position 2
#include "presetTwo.h"
//File for running autonomous in case of center goal in position 1
#include "presetThree.h"
//Sets the mode of the IRSeeker DC input
tHTIRS2DSPMode _mode = DSP_1200;

void initializeRobot()
{
	return;
} // end of initialization

//This is where the program is changed during the competition
//We will have many different files with different parts of this commented
//It will automatically run the correct program
void autoType()
{
	//Starting on blue ramp
	//blue = 1;
	//ramp = 1;

	//Starting on blue floor
	blue = 1;
	ramp = 0;

	//Starting on red ramp
	//red = 1;
	//ramp = 1;

	//Starting on red floor
	//red = 1;
	//ramp = 0;

	//Redundancy to prevent freak errors in the program
	if(blue == 1)
		red = 0;
	if(red == 1)
		blue = 0;
}

task main()
{
	initializeRobot();            //Initialize the robot
	disableDiagnosticsDisplay();	//Turns off the Diagnostics display
	//startTask(autonomousChooser); //Starts autonomous chooser
	//waitForStart();               //Importante!
	//stopTask(autonomousChooser);  //Ends autonomous chooser
	startTask(emergency);         //Starts emergency task in case quick stop is needed
	autoType();                   //Manual preset input
	//startPos();                   //Finds initial readings
	preset = 3;
	option3 = 'a';
	if(preset == 1)               //If the preset is determined to be 1
		presetOne();                //Then run the presetOne
	else if(preset == 2)          //If the preset is determined to be 2
		presetTwo();                //Then run the presetTwo
	else if(preset == 3)          //If the preset is determined to be 3
		presetThree();              //Then run the presetThree
	while(true){wait1Msec(10);}   //Infinite loop until the end of autonomous period
}
