#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initializeRobot(){
	return;
}
task rolling ()
{
	clearTimer(T1);
	clearTimer(T2);
	while(time10[T1] < 500)
	{
		motor[motorFL]= 50;
		motor[motorBL]= 50;
		motor[motorFR]= 50;
		motor[motorBR]= 50;
	}
	while(time10[T2] < 1000)
	{
		motor[motorFL]= -50;
		motor[motorBL]= 0;
		motor[motorFR]= 0;
		motor[motorBR]= -50;
	}
}
task main()
{
	initializeRobot();
	startTask(rolling);
}
