#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogInactive)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     Sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorFR,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int _dirDC = 0;
int _dirAC = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;
int irNear = 0;
int irFar = 0;
int irDist = 0;
int irTotal = 0;
int preset = 0;
int num = 0;
int ramp = 0;
int red = 0;
int blue = 0;
int irMax = 0;

float ultsonar = 0.0;
int irTotalOld = 0;
int alignDir = 20;
int final = 0;
int count = 1;
char option = 'a';
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;

#include "JoystickDriver.c"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "emergency.h"
#include "doneReset.h"
#include "liftCenter.h"
#include "floorOneAStrafe.h"
#include "floorOneAKick.h"
#include "moveSonar.h"
#include "floorOneAAlign.h"
#include "floorOneBMove.h"
#include "startPos.h"
#include "presetOne.h"
#include "presetTwo.h"
#include "presetThree.h"

tHTIRS2DSPMode _mode = DSP_1200;

void initializeRobot()
{
	return;
} // end of initialization

void autoType()
{
	//Starting on blue ramp
	//blue = 1;
	//ramp = 1;

	//Starting on blue floor
	blue = 1;
	ramp = 0;

	//Starting on red ramp
	//red = 1;
	//ramp = 1;

	//Starting on red floor
	//red = 1;
	//ramp = 0;

	//Option A
	//option = "a";

	//Option B
	option = 'b';

	//Option C
	//option = "c";

	if(blue == 1)
		red = 0;
	if(red == 1)
		blue = 0;
}

task main()
{
	initializeRobot();
	//waitForStart();
	startTask(emergency);
	autoType();
	startPos();
	if(preset == 1)
		one();
	else if(preset == 2)
		startTask(two);
	else if(preset == 3)
		three();
	while(true){wait1Msec(10);}
}
