#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLeftPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorRightPulley, tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S4_C1_1,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoRearGrabberR,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servoRearGrabberL,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servo1,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
int _dirAC = 0;
int _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"

void initializeRobot()
{

}

task main()
{
	initializeRobot();
	//^^^TESTING
	//disableDiagnosticsDisplay();
	//startTask(autonomousChooserSimple);
	//while(true){wait1Msec(100);}
	waitForStart();
	initializeLift();
	//stopTask(autonomousChooserSimple)
	/*ramp = true;
	if(!ramp)
	{
		heading = 180;
		//Initializes Servos to initial values
		initializeServos();
		//Lifts the lift slightly off of the ground
		initializeLift();
		//Moves the servos slightly forward to make sure the ablls dont roll out
		setServos(50);
		wait1Msec(1000);
		//Moves the robot near the medium tube
		//moveRobotBRamp(-20, 2.4); //Move down the ramp
		//moveRobotBR(-20,1); //Move back more
		//lift60(); //Lift the balls to the tube
		//setServos(100); //Drop the balls
		//setServos(0); //Raise the lift back up
		//moveRobotBR(20,1); //Move robot back forward
		//lower60(); //Lower the lift
		//gyroTurn(false,45,90); //Turn to the right 90 degrees
		//Now you should be facing the center structure
		moveRobotBR(30,1); //Move forward for better readings
		irTotal = readIR(); //Read the IR value
		_dirAC = HTIRS2readACDir(HTIRS2);
		if(_dirAC == 5) //If preset 1
		{
			gyroTurn(false,30,45); //Turn right 45 degrees
			moveRobotBR(30,1); //Go forward
			gyroTurn(true,30,95); //Turn right 45 degrees
			hitKickstand();
			////LATER
			//gyroTurn(true,30,90);
			//moveRobotBR(30,2);
			//gyroTurn(true,30,45);
			//moveRobotBR(20,3);
		}
		else if(_dirAC > 1) //If preset 2
		{
			moveRobotBR(30,0.55); //Move forward a bit
			gyroTurn(false,30,7); //Turn 45 degrees to the left
			hitKickstand();
			//gyroTurn(true,30,90);
			//moveRobotBR(20,3);
		}
		else //If preset 3
		{
			gyroTurn(false,30,45); //Turn 45 degrees right
			moveRobotBR(30,1.7); //Move forward
			gyroTurn(true,30,200); //Rotate 135 degrees to the left
			hitKickstand();
			//gyroTurn(false,30,45);
			//moveRobotBR(20,2.5);
		}
		while(true){wait1Msec(100);}
	}
	else
	{*/
		motor[motorFL] = -50;
		motor[motorBL] = -50;
		motor[motorFR] = -50;
		motor[motorBR] = -50;
		wait1Msec(2500);
		stopMotors();
	//}
}
