#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeftPulleyT, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorManipulator, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorRightPulley, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorRightPulleyT, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoRearGrabberR,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servoManipRight,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_5,    servoRearGrabberL,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servoManipLeft,       tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
int _dirAC = 0;
int _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"

void initializeRobot()
{
	HTGYROstartCal(HTGYRO);
	initializeServos(); //Initializes Servos to initial values
	initializeLift(); //Lifts the lift slightly off of the ground
	releaseGoal();
}

task timer()
{
	clearTimer(T3);
	while(time1[T3] < 30000)
	{
		wait1Msec(100);
	}
	while(true){
	motor[motorFL] = 0;
	motor[motorBL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = 0;
	motor[motorRightPulley] = 0;
	//motor[motorLeftPulley] = 0;
	nVolume = 4;
	playSound(soundBeepBeep);
	}
}
task main()
{
	/*bool goodBacons = true;
	string goodBacon = "No";
	while(nNxtButtonPressed != 3)
	{
		clearScreen();
		nxtDisplayTextLine(2,"Good IR bacons?");
		nxtDisplayCenteredBigTextLine(5,"%s",goodBacon);
		if(nNxtButtonPressed == 1 || nNxtButtonPressed == 2)
		{
			if(goodBacon == "No")
				goodBacon = "Yes";
			else if(goodBacon == "Yes")
				goodBacon = "No";
		}
	}
	if(goodBacon == "No")
		goodBacons = false;
	else
		goodBacons = true;
	string display = "";
	if(goodBacons)
		display = "true";
	else
		display = "false";
	nxtDisplayCenteredBigTextLine(5,"%s",display);*/
	//waitForStart();
//while(true)
//{
//	initializeServos();
//	wait1Msec(5);
//}
//waitForStart();
	initializeRobot();
	HTGYROstartCal(HTGYRO);
	//wait1Msec(5);
	//startTask(timer);
	moveRobotBL(30,1.2); //Move forward for better readings
	//while(true){wait1Msec(50);}
	string param1 = "acS2";
	string param2 = "acS3";
	string param3 = "acSector";
	float newACS2 = readIrNew(param1);
	float newACS3 = readIrNew(param2);
	float newAcSect = readIrNew(param3);
	nxtDisplayCenteredBigTextLine(5,"%d",newACS2);
	////preset 3
	//newACS2 = 10;
	//newACS3 = 30;
	////preset 2
	//newACS2 = 13;
	//newACS3 = 30;
	//preset 1
	//newACS2 = 0;
	//newACS3 = 0;
	bool goodBacons = true;
	if(goodBacons)
	{
		if(newACS3 > 50) //If preset 3
		{
			gyroTurn(55,170); //Turn 180 degrees
			upCenter(); //Raise the lift to the center goal
			moveRobotBL(-20,0.72); //Back up to center goal
			dumpBalls(); //Dump the balls in the center goal
			moveRobotBL(30,0.48); //Move back forwards
			lowerCenter(); //Lower the lift to the floor
			gyroTurn(45,-90); //Turn 90 degrees to the left
			moveRobotBL(45,0.75); //Move forwards
			gyroTurn(45,-65); //Turn 70 degrees to the left
			hitKickstand(); //Run into the kickstand
		}
		else if(newACS2 > 12 || newACS3 > 15) //If preset 2
		{
			gyroTurn(30,-45); //Turn Left 45 degrees
			moveRobotBL(30,1.32); //Move forward
			gyroTurn(30,-71); //Turn Left 62.5 degrees
			upCenter(); //Raise the lift to the center goal
			moveRobotBL(-20,0.450); //Back up to the center goal
			dumpBalls(); //Dump the balls i`n the center goal
			moveRobotBL(20,0.5); //Move away from the center goal
			lowerCenter(); //Lower the lift
			gyroTurn(45,-90); //Turn 90 degrees to the left
			moveRobotBL(45,0.75); //Move forwards
			gyroTurn(45,-66); //Turn 90 degrees to the left
			hitKickstand(); //Run into the kickstand
		}
		else //If preset 1
		{
			gyroTurn(30,-37); //Turn Left 45 Degrees
			moveRobotBL(30,2.24); //Move forward
			gyroTurn(30,-57); //Turn Left 45 Degrees
			upCenter(); //Raise the lift to the center goal
			moveRobotBL(-20,0.420); //Back up to the center goal
			dumpBalls(); //Dump the balls in the center goal
			lowerCenter(); //Lower the lift
			//moveRobotBL(20,0.5); //Move away fm the center goal
			gyroTurn(45,-90); //Turn 90 degrees to the left
			moveRobotBL(45,0.63); //Move forwards
			gyroTurn(45,-50); //Turn 70 degrees to the left
			hitKickstand(); //Run into the kickstand
		}
	}
	else
	{
		if(newAcSect != 5 && newAcSect != 0) //If preset 2
		{
			gyroTurn(30,-45); //Turn Left 45 degrees
			moveRobotBL(30,1.3); //Move forward
			gyroTurn(30,-71); //Turn Left 62.5 degrees
			upCenter(); //Raise the lift to the center goal
			moveRobotBL(-20,0.285); //Back up to the center goal
			dumpBalls(); //Dump the balls in the center goal
			moveRobotBL(20,0.5); //Move away from the center goal
			lowerCenter(); //Lower the lift
			gyroTurn(45,-90); //Turn 90 degrees to the left
			moveRobotBL(45,0.75); //Move forwards
			gyroTurn(45,-70); //Turn 90 degrees to the left
			hitKickstand(); //Run into the kickstand
		}
		else if(newAcSect == 5) //If preset 3
		{
			gyroTurn(55,170); //Turn 180 degrees
			upCenter(); //Raise the lift to the center goal
			moveRobotBL(-20,0.66); //Back up to center goal
			dumpBalls(); //Dump the balls in the center goal
			moveRobotBL(30,0.48); //Move back forwards
			lowerCenter(); //Lower the lift to the floor
			gyroTurn(45,-90); //Turn 90 degrees to the left
			moveRobotBL(45,0.75); //Move forwards
			gyroTurn(45,-65); //Turn 70 degrees to the left
			hitKickstand(); //Run into the kickstand
		}
		else //If preset 1
		{
			gyroTurn(30,-37); //Turn Left 45 Degrees
			moveRobotBL(30,2.15); //Move forward
			gyroTurn(30,-57); //Turn Left 45 Degrees
			upCenter(); //Raise the lift to the center goal
			moveRobotBL(-20,0.365); //Back up to the center goal
			dumpBalls(); //Dump the balls in the center goal
			lowerCenter(); //Lower the lift
			//moveRobotBL(20,0.5); //Move away fm the center goal
			gyroTurn(45,-90); //Turn 90 degrees to the left
			moveRobotBL(45,0.63); //Move forwards
			gyroTurn(45,-65); //Turn 70 degrees to the left
			hitKickstand(); //Run into the kickstand
		}
	}
	while(true){wait1Msec(100);}
}
