#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogInactive)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeftPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorRightPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servoLeftBridge,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

task main()
{
	while(true){
		servo[servoLeftBridge] = 255;
		servo[servoRightBridge] = 127;
		wait1Msec(3000);

		servo[servoLeftBridge] = 0;
		servo[servoRightBridge] = 255;
		wait1Msec(3000);
	}
























	//motor[motorFL] = 100;
	//motor[motorBL] = 100;
	//motor[motorFR] = 100;
	//motor[motorBR] = 100;
	//motor[motorManipulator] = 100;
	//motor[motorLeftPulley] = 100;
	//motor[motorRightPulley] = 100;
	//motor[motorNull] = 100;
	//wait1Msec(30000000000);
	//while(true){
	//getJoystickSettings(joystick);
	//int x1 = joystick.joy1_x1;
	//int y1 = joystick.joy1_y1;
	//int x2 = joystick.joy1_x2;
	//int y2 = joystick.joy1_y2;
	//int joy2y1 = joystick.joy2_y1;
	//int joy2y2 = joystick.joy2_y2;
	//////Servo Right Bridge?
	////if(servoValue[servoRightBridge] > 200)
	//if(y2 > 10)
	//	{
	//		servo[servoLeftBridge] = servoValue[servoLeftBridge] + 10;
	//		servo[servoRightBridge] = servoValue[servoRightBridge] + 10;
	//		wait1Msec(100);
	//	}
	//else if(y2 < 10)
	//{
	//	servo[servoLeftBridge] = servoValue[servoLeftBridge] - 10;
	//	servo[servoRightBridge] = servoValue[servoRightBridge] - 10;
	//	wait1Msec(100);
	//}
	////Servo Left Bridge?
	//if(servoValue[servoLeftBridge] > 100)
		//servo[servoLeftBridge] = servoValue[servoLeftBridge] - 50;
	//else
		//servo[servoLeftBridge] = servoValue[servoLeftBridge] + 50;
	////Servo Null1?
	//if(servoValue[servoNull1] > 100)
	//	servo[servoNull1] = servoValue[servoNull1] + 50;
	//else
	//	servo[servoNull1] = servoValue[servoNull1] - 50;
	////Servo Null2?
	//if(servoValue[servoNull2] > 100)
	//	servo[servoNull2] = servoValue[servoNull2] + 50;
	//else
	//	servo[servoNull2] = servoValue[servoNull2] - 50;
	////Servo Null3?
	//if(servoValue[servoNull3] > 100)
	//	servo[servoNull3] = servoValue[servoNull3] + 50;
	//else
	//	servo[servoNull3] = servoValue[servoNull3] - 50;
	////Servo Null4?
	//if(servoValue[servoNull4] > 100)
	//	servo[servoNull4] = servoValue[servoNull4] + 50;
	//else
	//	servo[servoNull4] = servoValue[servoNull4] - 50;
	//}
	while(true){wait1Msec(100);}
}
