#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     BR,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initializeRobot(){
	return;
} // end of initialization

short FL = 0;
short FR = 0;
short BL = 0;
short BR = 0;

short threshold = 15;
short y1 = 0;
short x1 = 0;
short x2 = 0;

task drive()
{
	while (true){
		y1 = joystick.joy1_y1;
		x1 = joystick.joy1_x1;
		x2 = joystick.joy1_x2;

		motor[FR] = y1 - x2 - x1;
		motor[BR] =  y1 - x2 + x1;
		motor[FL] = y1 + x2 + x1;
		motor[BL] =  y1 + x2 - x1;

		if (motor[FR] < 100)
		{
			motor[FR] = y1;
		} // End of if
		else
		{
			motor[FR] = 100;
		} // End of else
		if (motor[FR] > -100)
		{
			motor[FR] = y1;
		} // End of if
		else
		{
			motor[FR] = -100;
		} // End of else

		//******************8

		if (motor[FL] < 100)
		{
			motor[FL] = y1;
		} // End of if
		else
		{
			motor[FL] = 100;
		} // End of else
		if (motor[FL] > -100)
		{
			motor[FL] = y1;
		} // End of if
		else
		{
			motor[FR] = -100;
		} // End of else

				//******************8

		if (motor[BR] < 100)
		{
			motor[BR] = y1;
		} // End of if
		else
		{
			motor[BR] = 100;
		} // End of else
		if (motor[FL] > -100)
		{
			motor[BR] = y1;
		} // End of if
		else
		{
			motor[BR] = -100;
		} // End of else

						//******************8

		if (motor[BL] < 100)
		{
			motor[BL] = y1;
		} // End of if
		else
		{
			motor[BL] = 100;
		} // End of else
		if (motor[FL] > -100)
		{
			motor[BL] = y1;
		} // End of if
		else
		{
			motor[BL] = -100;
		} // End of else



		task main()
		{
			initializeRobot();
			waitForStart();
			startTask(Holodrive);
			while(true){}

		}
	}
