#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeftPulleyT, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLeftPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorRightPulleyT, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorRightPulley, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoRearGrabberR,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servoManipRight,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_5,    servoRearGrabberL,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servoManipLeft,       tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
int _dirAC = 0;
int _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"

void initializeRobot()
{
	HTGYROstartCal(HTGYRO);
	initializeServos(); //Initializes Servos to initial values
	initializeLift(); //Lifts the lift slightly off of the ground
	releaseGoal();
}

task timer()
{
	clearTimer(T3);
	while(time1[T3] < 30000)
	{
		wait1Msec(100);
	}
	while(true){
	motor[motorFL] = 0;
	motor[motorBL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = 0;
	motor[motorRightPulley] = 0;
	motor[motorLeftPulley] = 0;
	nVolume = 4;
	playSound(soundBeepBeep);
	}
}

task main()
{
	waitForStart();
	initializeRobot();
	//startTask(timer);
	moveRobotBL(30,0.75); //Move forward for better readings
	float newACS2 = readIrNew("acS2");
	float newACS3 = readIrNew("acS3");
	//Lifting to medium goal while moving:
	//void moveRobotLift(float speed, float rot, int height)
	//moveRobotLift(30,4,2400);
	float newACS2 = 12;
	if(newACS2 > 11) //If preset 2 (Diagonal)
	{
		gyroTurn(30,30); //Turn Right 30 degrees
		moveRobotBL(30,3); //Move forward
		gyroTurn(30,-90); //Turn Left 90 degrees
		moveRobotBLGrab(-30,1.5); //Grab the medium goal
		moveRobotBL(20,0.8); //Pull it forward
		gyroTurn(30,60); //Turn 60 degrees left
		moveRobotLift(40,4); //Move back towards the parking zone
		gyroTurn(30,150); //Rotate 150 degrees right
		moveRobotBL(-30,0.5); //Move back
		releaseGoal(); //Let go of goal
		moveRobotBL(30,0.5); //Move forward
		gyroTurn(30,30); //Turn right 30 degrees
		moveRobotBL(30,4); //Move forward
		gyroTurn(30,150); //Turn right 150 degrees
		moveRobotBLGrab(-30,1.5); //Grab the tall goal
		moveRobotBL(30,1.5);
		gyroTurn(30,30); //Turn right 30 degrees;
		hitKickstand(); //Run into the kickstand
		hitKickstand(); //EXTRA SURE
	}
	else if(newACS3 > 25) //If preset 3 (Center goal straight ahead)
	{
		gyroTurn(55,165); //Turn around
		upCenter(); //Raise the lift to the center goal
		moveRobotBL(-20,1.14); //Back up to center goal
		dumpBalls(); //Dump the balls in the center goal
		moveRobotBL(30,0.5); //Move back forwards
		lowerCenter(); //Lower the lift to the floor
		gyroTurn(45,-90); //Turn 90 degrees to the left
		moveRobotBL(45,0.5); //Move forwards
		gyroTurn(45,-60); //Turn 90 degrees to the left
		//gyroTurn(40,-15); //Turn an additional 20 degrees to the left
		hitKickstand(); //Run into the kickstand
		//liftToGround();
	}
	else //If preset 1 (Sideways)
	{
		gyroTurn(30,-45); //Turn Left 45 Degrees
		moveRobotBL(30,3.15); //Move forward
		gyroTurn(30,-45); //Turn Left 45 Degrees
		moveRobotBL(-30,0.75); //Back up to the center goal
		upCenter(); //Raise the lift to the center goal
		moveRobotBL(-20,0.4); //Back up to the center goal
		dumpBalls(); //Dump the balls in the center goal
		moveRobotBL(20,0.5); //Move away form the center goal
		lowerCenter(); //Lower the lift
		gyroTurn(45,-90); //Turn Left 90 Degrees
		moveRobotBL(45,0.35); //Move forward
		gyroTurn(45,-50); //Turn Left 90 degrees
		hitKickstand(); //Run into the kickstand
	}
	while(true){wait1Msec(100);}
}
