#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeftPulleyT, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLeftPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorRightPulleyT, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorRightPulley, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoRearGrabberR,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servoManipRight,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_5,    servoRearGrabberL,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servoManipLeft,       tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
int _dirAC = 0;
int _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"

void initializeRobot()
{
	HTGYROstartCal(HTGYRO);
	initializeServos(); //Initializes Servos to initial values
	initializeLift(); //Lifts the lift slightly off of the ground
	releaseGoal();
}

task timer()
{
	clearTimer(T3);
	while(time1[T3] < 30000)
	{
		wait1Msec(100);
	}
	while(true){
	motor[motorFL] = 0;
	motor[motorBL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = 0;
	motor[motorRightPulley] = 0;
	//motor[motorLeftPulley] = 0;
	nVolume = 4;
	playSound(soundBeepBeep);
	}
}

task main()
{
	wait1Msec(2500);
	//grabGoal();
	//wait1Msec(1000);
	//moveRobotLift(40,4,2400); //Move back towards the parking zone
	//while(true){wait1Msec(500);}
	waitForStart();
	initializeRobot();
	//startTask(timer);
	/*while(true){
	gyroTurn(30,45);
	wait1Msec(500);
	gyroTurn(30,-45);
	wait1Msec(500);
}*/
//HTGYROstartCal(HTGYRO);
	moveRobotBL(30,0.75); //Move forward for better readings
	motor[motorFL] = 0;
	motor[motorBL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = 0;
	string param1 = "acS2";
	string param2 = "acS3";
	float newACS2 = readIrNew(param1);
	float newACS3 = readIrNew(param2);
	//Lifting to medium goal while moving:
	//void moveRobotLift(float speed, float rot, int height)
	//moveRobotLift(30,4,2400);
	newACS2 = 10;
	newACS3 = 30;
	if(newACS2 > 11) //If preset 2 (Diagonal)
	{
		//moveRobotBL(30,0.5); //Move forward a bit
		//gyroTurn(30,-140); //Turn Right 30 degrees
		//moveRobotBLGrabLong(-30,5.4); //Move back towards medium goal
		gyroTurn(30,-135); //Turn 135 degrees left
		moveRobotBL(-30,3); //Move backwards 4.75 rotations
		gyroTurn(30,-40); //Turn 50 degrees left
		moveRobotBL(-30,3); //Back up to small goal
		moveRobotBLGrabLate(-30,1); //Back up and grab the goal
		grabGoal();
		moveRobotBL(30,1);
		lift30();
		moveRobotBL(30,2);
		gyroTurn(30,35);
		//wait1Msec(750);
		//moveRobotLift(40,5,2800);
		moveRobotBL(40,3);
		/*motor[motorRightPulley] = 0;
		motor[motorRightPulleyT] = 0;
		motor[motorLeftPulley] = 0;
		motor[motorLeftPulleyT] = 0;*/
		gyroTurn(30,130); //Turn Right 120 degrees
		//moveRobotBL(-30,1);
		releaseGoal();
		moveRobotBL(30,1); //Move forward
		gyroTurn(30,45); //Turn right 45 degrees
		hitKickstand();
		/*moveRobotBL(30,0.5);
		gyroTurn(30,-120);
		moveRobotBL(-30,5.2); //Move back towards tall goal
		grabGoal();
		//moveRobotBL(30,4); //Move forward
		//gyroTurn(30,180); //Turn Left 90 degrees
		moveRobotBLGrab(-30,1.25); //Grab the medium goal
		moveRobotBL(20,0.8); //Pull it forward
		gyroTurn(30,-60); //Turn 60 degrees left
		moveRobotLift(40,4,2800); //Move back towards the parking zone
		motor[motorRightPulley] = 0;
		motor[motorRightPulleyT] = 0;
		motor[motorLeftPulley] = 0;
		motor[motorLeftPulleyT] = 0;
		gyroTurn(30,150); //Rotate 150 degrees right
		moveRobotBL(-30,0.5); //Move back
		releaseGoal(); //Let go of goal
		moveRobotBL(30,0.5); //Move forward
		gyroTurn(30,30); //Turn right 30 degrees
		moveRobotBL(30,4); //Move forward
		gyroTurn(30,150); //Turn right 150 degrees
		moveRobotBLGrab(-30,1.5); //Grab the tall goal
		moveRobotBL(30,1.5);
		gyroTurn(30,30); //Turn right 30 degrees;
		hitKickstand(); //Run into the kickstand
		hitKickstand(); //EXTRA SURE*/
	}
	else if(newACS3 > 25) //If preset 3 (Center goal straight ahead)
	{
		//moveRobotBL(30,0.5); //Move forward a bit
		//gyroTurn(30,-140); //Turn Right 30 degrees
		//moveRobotBLGrabLong(-30,5.4); //Move back towards medium goal
		gyroTurn(30,-135); //Turn 135 degrees left
		moveRobotBL(-30,3); //Move backwards 4.75 rotations
		gyroTurn(30,-40); //Turn 50 degrees left
		moveRobotBL(-30,3); //Back up to small goal
		moveRobotBLGrabLate(-30,1); //Back up and grab the goal
		grabGoal();
		moveRobotBL(30,1);
		lift30();
		moveRobotBL(30,2);
		gyroTurn(30,35);
		//wait1Msec(750);
		//moveRobotLift(40,5,2800);
		moveRobotBL(40,3);
		/*motor[motorRightPulley] = 0;
		motor[motorRightPulleyT] = 0;
		motor[motorLeftPulley] = 0;
		motor[motorLeftPulleyT] = 0;*/
		gyroTurn(30,130); //Turn Right 120 degrees
		//moveRobotBL(-30,1);
		releaseGoal();
		gyroTurn(30,45); //Turn right 45 degrees
		moveRobotBL(30,1.1); //Move forward a bit
		gyroTurn(30,-45); //Turn left 45 degrees
		hitKickstand(); //Run into the kickstand
	}
	else //If preset 1 (Sideways)
	{
		//moveRobotBL(30,0.5); //Move forward a bit
		//gyroTurn(30,-140); //Turn Right 30 degrees
		//moveRobotBLGrabLong(-30,5.4); //Move back towards medium goal
		gyroTurn(30,-135); //Turn 135 degrees left
		moveRobotBL(-30,3); //Move backwards 4.75 rotations
		gyroTurn(30,-40); //Turn 50 degrees left
		moveRobotBL(-30,3); //Back up to small goal
		moveRobotBLGrabLate(-30,1); //Back up and grab the goal
		grabGoal();
		moveRobotBL(30,1);
		lift30();
		moveRobotBL(30,2);
		gyroTurn(30,35);
		//wait1Msec(750);
		//moveRobotLift(40,5,2800);
		moveRobotBL(40,3);
		/*motor[motorRightPulley] = 0;
		motor[motorRightPulleyT] = 0;
		motor[motorLeftPulley] = 0;
		motor[motorLeftPulleyT] = 0;*/
		gyroTurn(30,130); //Turn Right 120 degrees
		//moveRobotBL(-30,1);
		releaseGoal();
		gyroTurn(30,30); //Turn right 45 degrees
		moveRobotBL(30,1.5); //Move forward
		gyroTurn(30,-120); //Turn left 135 degrees
		hitKickstand(); //Run into the kickstand
		/*moveRobotBL(30,0.5);
		gyroTurn(30,-120);
		moveRobotBL(-30,5.2); //Move back towards tall goal
		grabGoal();
		//moveRobotBL(30,4); //Move forward
		//gyroTurn(30,180); //Turn Left 90 degrees
		moveRobotBLGrab(-30,1.25); //Grab the medium goal
		moveRobotBL(20,0.8); //Pull it forward
		gyroTurn(30,-60); //Turn 60 degrees left
		moveRobotLift(40,4,2800); //Move back towards the parking zone
		motor[motorRightPulley] = 0;
		motor[motorRightPulleyT] = 0;
		motor[motorLeftPulley] = 0;
		motor[motorLeftPulleyT] = 0;
		gyroTurn(30,150); //Rotate 150 degrees right
		moveRobotBL(-30,0.5); //Move back
		releaseGoal(); //Let go of goal
		moveRobotBL(30,0.5); //Move forward
		gyroTurn(30,30); //Turn right 30 degrees
		moveRobotBL(30,4); //Move forward
		gyroTurn(30,150); //Turn right 150 degrees
		moveRobotBLGrab(-30,1.5); //Grab the tall goal
		moveRobotBL(30,1.5);
		gyroTurn(30,30); //Turn right 30 degrees;
		hitKickstand(); //Run into the kickstand
		hitKickstand(); //EXTRA SURE*/
	}
	while(true){wait1Msec(100);}
}
