#pragma config(Sensor, S1,     Gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-gyro.h"
task gyro ()
{
	while(true) {
		if (time1[T1] > 1000) {
			eraseDisplay();
			nxtDisplayTextLine(1, "Resetting");
			nxtDisplayTextLine(1, "offset");
			wait1Msec(500);
			short HTGYRO = 0;
			// Start the calibration and display the offset
			nxtDisplayTextLine(2, "Offset: %f", HTGYROstartCal(HTGYRO));
			PlaySound(soundBlip);
			while(bSoundActive) EndTimeSlice();
			time1[T1] = 0;
		}

		while(nNxtButtonPressed != kEnterButton) {
			eraseDisplay();

			nxtDisplayTextLine(1, "Reading");
			// Read the current calibration offset and display it
			nxtDisplayTextLine(2, "Offset: %4f", HTGYROreadCal(HTGYRO));

			nxtDisplayClearTextLine(4);
			// Read the current rotational speed and display it
			nxtDisplayTextLine(4, "Gyro:   %4f", HTGYROreadRot(HTGYRO));
			wait1Msec(100);
		}
	}
}
task main()
{
	wait1Msec(500);
	startTask(gyro);
	while (true)
	{
	}
}
