#pragma config(Sensor, S1,     HTGYRO,              sensorAnalogInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* $Id: hitechnic-gyro-test1.c 133 2013-03-10 15:15:38Z xander $
*/

/**
* hitechnic-gyro.h provides an API for the HiTechnic Gyroscopic Sensor.  This program
* demonstrates how to use that API.
*
* Changelog:
* - 0.1: Initial release
* - 0.2: More comments
* - 0.3: Removed common.h from includes
*
* Credits:
* - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
*
* License: You may use this code as you wish, provided you give credit where it's due.
*
* THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

* Xander Soldaat (xander_at_botbench.com)
* 20 February 2011
* version 0.3
*/

#include "drivers\hitechnic-gyro.h"

task main () {
	nxtDisplayTextLine(0, "HT Gyro");
	nxtDisplayTextLine(1, "Test 1");
	nxtDisplayTextLine(5, "Press enter");
	nxtDisplayTextLine(6, "to set relative");
	nxtDisplayTextLine(7, "heading");


	float position = 0;

	wait1Msec(2000);
	eraseDisplay();
	time1[T1] = 0;
	while(true) {
		if (time1[T1] > 1000) {
			eraseDisplay();
			nxtDisplayTextLine(1, "Resetting");
			nxtDisplayTextLine(1, "offset");
			wait1Msec(500);

			// Start the calibration and display the offset
			nxtDisplayTextLine(2, "Offset: %f", HTGYROstartCal(HTGYRO));
			position = 0;
			PlaySound(soundBlip);
			while(bSoundActive) EndTimeSlice();
			time1[T1] = 0;
		}

		while(nNxtButtonPressed != kEnterButton) {
			eraseDisplay();

			nxtDisplayTextLine(1, "Reading");
			// Read the current calibration offset and display it
			nxtDisplayTextLine(2, "Offset: %4f", HTGYROreadCal(HTGYRO));

			nxtDisplayClearTextLine(4);
			// Read the current rotational speed and display it
			nxtDisplayTextLine(4, "Gyro:   %4f", HTGYROreadRot(HTGYRO));
			nxtDisplayTextLine(6, "Press enter");
			nxtDisplayTextLine(7, "to recalibrate");

			float rotVel = HTGYROreadRot(HTGYRO);
			position = position + (rotVel  * .1);
			nxtDisplayTextLine(3, "Position:   %4f", position);
			wait1Msec(100);
		}
	}
}

	// To find how much we rotate off of origin/straight line movement, we take average velocity and multiply it by time


	/*
	* $Id: hitechnic-gyro-test1.c 133 2013-03-10 15:15:38Z xander $
	*/
