#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorFR,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int x1 = 0;
int y1 = 0;
int x2 = 0;
int joy2 = 0;
float num = 0.00;
float FL = 0.00;
float BL = 0.00;
float FR = 0.00;
float BR = 0.00;

#include "JoystickDriver.c"
#include "normalize.h"

void initializeRobot(){
	return;
} // end of initialization


task HoloDrive()
{
	while(true)
	{
		getJoystickSettings(joystick);
		x1 = joystick.joy1_x1;
		y1 = joystick.joy1_y1;
		x2 = joystick.joy1_x2;
		joy2 = joystick.joy2_y2;

		x1 = x1 / 1.28;
		y1 = y1 / 1.28;
		x2 = x2 / 1.28;
		joy2 = joy2 / 1.28;

		FL = y1 + x1 + x2;
		BL = y1 - x1 + x2;
		FR = y1 - x1 - x2;
		BR = y1 + x1 - x2;

		normalize();

		//All Motors at 3/5 speed
		FL = FL * 0.60;
		BL = BL * 0.60;
		FR = FR * 0.60;
		BR = BR * 0.60;

		if(joy1Btn(8))
		{
			FL = FL * 0.50;
			BL = BL * 0.50;
			FR = FR * 0.50;
			BR = BR * 0.50;
		}

		//Run the motors
		if(abs(x1) >= 10 || abs(y1) >= 10 || abs(x2) >= 10)
		{
			motor[motorFL] = FL;
			motor[motorBL] = BL;
			motor[motorFR] = -FR;
			motor[motorBR] = -BR;
		}
		else
		{
			motor[motorFL] = 0;
			motor[motorBL] = 0;
			motor[motorFR] = 0;
			motor[motorBR] = 0;
		}

		if(abs(joy2) >= 10)
			motor[motorManipulator] = joy2;
		else
			motor[motorManipulator] = 0;
		wait1Msec(7);
	}
}

task main()
{
	initializeRobot();
	waitForStart();
	startTask(HoloDrive);
	while(true){wait1Msec(1);}
} // End of task main
