#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     BR,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //includes joystick drivers

void initializeRobot(){
	return;
}

task HoloDrive()
{
	while(true){
		// Multiplying by 100/127 to convert input from controller joystick to output for motor
		short y1 = (joystick.joy1_y1*100.0/127.0);
		short x1 = (joystick.joy1_x1*100.0/127.0);
		short v = sqrt(x1*x1+y1*y1);

		// <a1,a2> + <b1,b2> = <x1,y1>
		// a1+b1 = x1
		// a2+b2 = y1
		// <5,7> + <4,10> = <9,17>
		// -b1 = b2
		// x1= 9; y1=17
		// a1+b1 = 9
		// a2+b2 = 17
		// a1= 9 - b1
		// 10- b1 - b1 = 17
		// -2b1 = 7
		// b1 = -3.5
		// a1 = 13.5
		// Forward movement and Backward movement
		// a1/b1
		// atan(abs(y1/x1)) = theta
		// (180 / PI) = radians to degrees
		// Q1: +5/+5
		// Q2:
		// Q3:
		// Q4:
		if(x1 > 5 && y1 > 5)
		{
		 	motor[FL] = v; //-v
			motor[FR] = v; // v
			motor[BL] = (((-2.222) * atan(abs(y1/x1)) + v)); // +v
			motor[BR] = -v; // -v
		} // End of if statement

		// Right movement and Left movement
		else if(x1 < -5 && y1 > 5)
		{
			motor[FL] = (100);
			motor[FR] = (((2.222) * atan(abs(y1/x1)) - 100));
			motor[BL] = (-100);
			motor[BR] = (((-2.222) * atan(abs(y1/x1)) + 100));
		} // End of else if statement
		else if(x1 < -5 && y1 < -5)
		{
			motor[FL] = (((-2.222) * atan(abs(y1/x1)) - 100));
			motor[FR] = (-100);
			motor[BL] = (((2.222) * atan(abs(y1/x1)) + 100));
			motor[BR] = (100);
		} // End of else if statement
		else if(x1 > 5 && y1 < -5)
		{
			motor[FL] = (-100);
			motor[FR] = (((-2.222) * atan(abs(y1/x1)) + 100));
			motor[BL] = (100);
			motor[BR] = (((2.222) * atan(abs(y1/x1)) - 100));
		} // End of else if statement
		else if(joy1Btn(7))
		{
			motor[FL] = -100;
			motor[FR] = -100;
			motor[BL] = -100;
			motor[BR] = -100;
		} // End of else if statement
		else if(joy1Btn(8))
		{
			motor[FL] = 100;
			motor[FR] = 100;
			motor[BL] = 100;
			motor[BR] = 100;
		} // End of else if statement
		else {
			motor[FL] = (0);
			motor[FR] = (0);
			motor[BL] = (0);
			motor[BR] = (0);
		} // End of else statement
	} // End of while(true)
} // End of task HoloDrive{}

task main()
{
	initializeRobot();

	waitForStart();
	startTask(HoloDrive);
} // End of task main
