#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot(){
	return;
} // end of initialization

float normalize(FL, BL, FR, BR)
{
	task HoloDrive()
	{
		int x1 = 0;
		int y1 = 0;
		int x2 = 0;
		float num = 0.00;
		float FL = 0.00;
		float BL = 0.00;
		float FR = 0.00;
		float BR = 0.00;
		while(true)
		{
			x1 = joystick.joy1_x1;
			y1 = joystick.joy1_y1;
			x2 = joystick.joy1_x2;

			x1 = (x1 / 127) * 100;
			y1 = (y1 / 127) * 100;
			x2 = (x2 / 127) * 100;

			FL = y1 - x1 + x2;
			BL = y1 - x1 + x2;
			FR = y1 - x1 - x2;
			BR = y1 - x1 - x2;

			if(abs(FL) >= BL && abs(FL) >= FR && abs(FL) >= BR && abs(FL) > 100)
			{
				num = FL / 100;
				FL = FL / num;
				BL = BL / num;
				FR = FR / num;
				BR = BR / num;
			} // end of if
			if(abs(BL) >= FL && abs(BL) >= FR && abs(BL) >= BR && abs(BL) > 100)
			{
				num = BL / 100;
				FL = FL / num;
				BL = BL / num;
				FR = FR / num;
				BR = BR / num;
			} // end of if
			if(abs(FR) >= FL && abs(FR) >= BL && abs(FR) >= BR && abs(FR) > 100)
			{
				num = FR / 100;
				FL = FL / num;
				BL = BL / num;
				FR = FR / num;
				BR = BR / num;
			} // end of if
			if(abs(BR) >= FL && abs(BR) >= BL && abs(BR) >= FR && abs(BR) > 100)
			{
				num = BR / 100;
				FL = FL / num;
				BL = BL / num;
				FR = FR / num;
				BR = BR / num;
			} // end of if
			motor[motorFL] = FL;
			motor[motorBL] = BL;
			motor[motorFR] = FR;
			motor[motorBR] = BR;
		}
	}

	task main()
	{
		initializeRobot();
		waitForStart();
		startTask(HoloDrive);
	} // End of task main
}
