#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeftPulleyT, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorManipulator, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorRightPulley, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorRightPulleyT, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoRearGrabberR,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servoManipRight,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_5,    servoRearGrabberL,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servoManipLeft,       tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
float _dirAC = 0;
float _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"

task timer()
{
	clearTimer(T3);
	while(time1[T3] < 30000)
	{
		wait1Msec(100);
	}
	while(true)
	{
		motor[motorFL] = 0;
		motor[motorBL] = 0;
		motor[motorFR] = 0;
		motor[motorBR] = 0;
		motor[motorRightPulley] = 0;
		motor[motorRightPulleyT] = 0;
		//motor[motorLeftPulley] = 0;
		motor[motorLeftPulleyT] = 0;
		nVolume = 4;
		playSound(soundBeepBeep);
	}
}

void initializeRobot() //Initializing robot
{
	HTGYROstartCal(HTGYRO);
	initializeServos(); //Initializes Servos to initial values
	initializeLift(); //Lifts the lift slightly off of the ground
	releaseGoal();
}

task main()
{
	//initializeRobot();
	//autonomousLift(3750);

	nMotorEncoder[motorLeftPulleyT] = 0;
	writeDebugStreamLine("%d",nMotorEncoder[motorLeftPulleyT]);
	while(true)
	{
		motor[motorRightPulley] = 75;
		motor[motorRightPulleyT] = 75;
		motor[motorLeftPulleyT] = 75;
		writeDebugStreamLine("%d",nMotorEncoder[motorLeftPulleyT]);
	}
	/*//moveRobotBL(30,1.2);
	while(true){
		string param1 = "acS2";
	string param2 = "acS3";
	string param3 = "acSector";
	string param4 = "acS4";
	float newACS2 = readIrNew(param1);
	float newACS3 = readIrNew(param2);
	float newAcSect = readIrNew(param3);
	float newACS4 = readIrNew(param4);
	writeDebugStreamLine("ACS2 %d", newACS2);
	writeDebugStreamLine("ACSECT %d",newAcSect);
	writeDebugStreamLine("ACS3 %d",newACS3);
	writeDebugStreamLine("ACS4 %d",newACS4);
	writeDebugStreamLine("\n");
}*/
	bool goodBacons = true;
	string goodBacon = "No";
	/*grabGoal();
	string param1 = "acS2";
	string param2 = "acS3";
	string param3 = "acSector";
	float newACS2 = readIrNew(param1);
	float newACS3 = readIrNew(param2);
	float acSect = readIrNew(param3);
	int preset = 0;
	if(acSect >= 5) //Preset 3
	{
		//gyroTurn(-30,30);
		//moveRobotBL(30,1.0);
		//gyroTurn(30,30);
		hitKickstand();
		hitKickstand();
	}
	else
	{
		moveRobotBL(30,0.5);
		if(goodBacons)
		{
			if(newACS3 > 25)
				preset = 1;
			else
				preset = 2;
		}
		else
		{
			if(acSect > 5)
				preset = 1;
			else
				preset = 2;
		}
		else if(preset == 2)
		{
			gyroTurn(-30,-30);
			moveRobotBL(30,1);
			gyroTurn(30,-45);
			hitKickstand();
		}
		else if(preset == 1)
		{
			hitKickstand():
			hitKickstand();
		}
	}*/

	while(nNxtButtonPressed != 3)
	{
		//clearScreen();
		nxtDisplayTextLine(2,"Good IR bacons?");
		nxtDisplayCenteredBigTextLine(5,"%s",goodBacon);
		if(nNxtButtonPressed == 1 || nNxtButtonPressed == 2)
		{
			if(goodBacon == "No")
				goodBacon = "Yes";
			else if(goodBacon == "Yes")
				goodBacon = "No";
		}
	}
	if(goodBacon == "No")
		goodBacons = false;
	else
		goodBacons = true;
	string display = "";
	if(goodBacons)
		display = "true";
	else
		display = "false";
	nxtDisplayCenteredBigTextLine(5,"%s",display);
	waitForStart();

	//grabGoal();
	//wait10Msec(readIRNew
	HTGYROstartCal(HTGYRO);
//while(true){

	//while(true){//nxtDisplayCenteredBigTextLine(newAcSect,"%d",5);
	wait1Msec(50);
	clearTimer(T1);
	//wait10Msec(500);
	initializeRobot(); //Intializes the robot for the start of autonomous
	HTGYROstartCal(HTGYRO);
	//startTask(timer); //Timer task for measuring how long the autonomous takes.
	moveRobotBLRamp(-25,3.5); //Move backwards down the ramp
	//moveRobotBLRamp(60,3.5); //Move forwards down the ramp
	/*wait1Msec(1000);
	gyroTurn(-30,30);
	//gyroTurn(-45,30);
	moveRobotBL(-30,1.27);
	gyroTurn(30,92);
	//gyroTurn(-30,90);
	moveRobotBLGrabLate(-30,2.35);
	grabGoal();
	moveRobotBL(30,1.5);*/
	wait1Msec(1000);
	gyroTurn(30,-75);
	alignWall();
	moveRobotBL(-30,1.25);
	gyroTurn(30,90);
	moveRobotBL(-30,1.6);
	gyroTurn(30,44);
	moveRobotBLGrabLate(-30,2);
	grabGoal();
	moveRobotBL(30,1.5);
	//autonomousLift(3750);
	/*while(true){
		string yolo = "acSector";
		float sector = readIrNew(yolo);
		nxtDisplayCenteredBigTextLine(sector,"%d",sector);
	}*/
	autonomousLift(3750);
	string param1 = "acS2";
	string param2 = "acS3";
	string param3 = "acSector";
	float newACS2 = readIrNew(param1);
	float newACS3 = readIrNew(param2);
	float acSect = readIrNew(param3);
	int preset = 0;
	if(acSect > 5) //Preset 3
	{
		gyroTurn(-30,30);
		moveRobotBL(30,1.0);
		gyroTurn(30,30);
		hitKickstand();
	}
	else
	{
		moveRobotBL(30,0.5);
		if(goodBacons)
		{
			if(newACS3 > 25)
				preset = 1;
			else
				preset = 2;
		}
		else
		{
			if(newACS3 > 5)
				preset = 1;
			else
				preset = 2;
		}
		if(preset == 2)
		{
			gyroTurn(-30,-30);
			moveRobotBL(30,1);
			gyroTurn(30,-45);
			hitKickstand();
		}
		else if(preset == 1)
		{
			hitKickstand():
			hitKickstand();
		}
	}
	while(true){wait1Msec(100);}
}
