#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeftPulleyT, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorManipulator, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorRightPulleyT, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorRightPulley, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoRearGrabberR,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servoManipRight,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_5,    servoRearGrabberL,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servoManipLeft,       tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
int _dirAC = 0;
int _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"



task timer()
{
	clearTimer(T3);
	while(time1[T3] < 30000)
	{
		wait1Msec(100);
	}
	while(true)
	{
		motor[motorFL] = 0;
		motor[motorBL] = 0;
		motor[motorFR] = 0;
		motor[motorBR] = 0;
		motor[motorRightPulley] = 0;
		motor[motorRightPulleyT] = 0;
		//motor[motorLeftPulley] = 0;
		motor[motorLeftPulleyT] = 0;
		nVolume = 4;
		playSound(soundBeepBeep);
	}
}

void initializeRobot() //Inti
{
	HTGYROstartCal(HTGYRO);
	initializeServos(); //Initializes Servos to initial values
	initializeLift(); //Lifts the lift slightly off of the ground
	releaseGoal();
}

task main()
{
	//waitForStart();
	clearTimer(T1);
	//wait10Msec(500);
	initializeRobot(); //Intializes the robot for the start of autonomous
	HTGYROstartCal(HTGYRO);
	//startTask(timer); //Timer task for measuring how long the autonomous takes.
	moveRobotBLRamp(-40,4); //Move backwards down the ramp
	wait1Msec(1000);
	gyroTurn(-30,30);
	moveRobotBL(-30,0.82);
	gyroTurn(30,90);
	moveRobotBL(-30,1.5);
	moveRobotBL(30,1.5);
	while(true){
	wait1Msec(500); //Wait 0.5 seconds
}
	//lift60();
	moveRobotBL(30,0.4); //Move forwards
	lift60();
	gyroTurn(30,30); //Turn 45 degrees right
	moveRobotBL(30,5.2); //Move back towards parking zone
	//lift60(); //Lift balls into the 60 cm. goal
	gyroTurn(30,135); //Turn 120 degrees right
	moveRobotBL(-30,0.5);
	releaseGoal(); //Let go of goal
	moveRobotBL(30,0.5);
	//moveRobotBL(30,0.75); //Set up to read kickstand position
	string param1 = "acS2";
	string param2 = "acS3";
	float newACS2 = readIrNew(param1);
	float newACS3 = readIrNew(param2);
	if(newACS2 > 11) //If preset 2
	{
		moveRobotBL(30,1); //Move forward
		gyroTurn(30,45); //Turn right 45 degrees
		hitKickstand();
	}
	else if(newACS3 > 20) //If preset 3
	{
		gyroTurn(30,45); //Turn right 45 degrees
		moveRobotBL(30,1.1); //Move forward a bit
		gyroTurn(30,-45); //Turn left 45 degrees
		hitKickstand(); //Run into the kickstand
	}
	else //If preset 1
	{
		gyroTurn(30,30); //Turn right 45 degrees
		moveRobotBL(30,1.5); //Move forward
		gyroTurn(30,-120); //Turn left 135 degrees
		hitKickstand(); //Run into the kickstand
	}

	while(true){wait1Msec(100);}
}
