#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     Sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers\hitechnic-irseeker-v2.h"

task main()
	{
	float ultsonar = 0;
	while (true){
	ultsonar = SensorValue[IR];
	nxtDisplayTextLine(2, "%2.2f", ultsonar);

	}
	} // End of task main
