#pragma config(Sensor, S1,     HTIRS2,              sensorI2CCustom)
#pragma config(Sensor, S4,     Sonar,          sensorSONAR)
/*#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/

#include "drivers\JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"

void initializeRobot()
{

	return;
}


task ultsense (){
float ultsonar = 0;
	ultsonar = SensorValue[Sonar];
	nxtDisplayTextLine(1, "Sonar reading");
	nxtDisplayTextLine(2, "%2.2f", ultsonar);
}


task irsense(){
	while(true){
tHTIRS2DSPMode _mode = DSP_1200;
	int _dirDC = 0;
	int _dirAC = 0;
	int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
	int acS1, acS2, acS3, acS4, acS5 = 0;

		_dirDC = HTIRS2readDCDir(HTIRS2);
		_dirAC = HTIRS2readACDir(HTIRS2);
		if(!HTIRS2readAllDCStrength(HTIRS2, dcS1, dcS2, dcS3, dcS4, dcS5))
			wait1Msec(5);
		if(!HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS4))
			wait1Msec(5);

		nxtDisplayTextLine(3, "%d %d", acS3, dcS3);

	}
}

task main()
{
	initializeRobot();
	//waitForStart();
startTask(irsense);
	while(true){
	startTask(ultsense);
}



}
