#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogInactive)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeftPulley, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorRightPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servoLeftBridge,      tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
int _dirAC = 0;
int _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"

void initializeRobot()
{

}

task main()
{
	initializeRobot();
	//TESTING
	//TESTING
	//TESTING
	gyroTurn(false,30,90);
	while(true){wait1Msec(100);}
	//^^^TESTING
	disableDiagnosticsDisplay();
	startTask(autonomousChooserSimple);
	//while(true){wait1Msec(100);}
	waitForStart();
	stopTask(autonomousChooserSimple);
	if(ramp)
	{
		heading = 180;
		//Initializes Servos to initial values
		//initializeServos();
		////Lifts the lift slightly off of the ground
		//initializeLift();
		////Moves the servos slightly forward to make sure the ablls dont roll out
		//setServos(127);
		//wait1Msec(1000);
		//Moves the robot near the medium tube
		moveRobotBRamp(-20, 2.4);
		moveRobotBR(-20,1);
		//lift60();
		//moveRobotBR(-15,0.5);
		//setServos(100);
		//setServos(255);
		//moveRobotBR(15,0.5);
		//lower60();
		moveRobotBR(-20,0.5);
		gyroTurn(false,30,90);
		moveRobotBR(30,1);
		irTotal = readIR();
		wait1Msec(500);
		if(_dirAC == 5)
		{
			gyroTurn(true,30,45);
			wait1Msec(500);
			moveRobotBR(30,0.75);
			wait1Msec(500);
			gyroTurn(false,30,45);
			wait1Msec(500);
			moveRobotBR(50,4);
		}
		else if(_dirAC > 1)
		{
			moveRobotBR(30,0.75);
			wait1Msec(500);
			gyroTurn(false,30,45);
			wait1Msec(500);
			moveRobotBR(50,4);
		}
		else
		{
			gyroTurn(true,30,45);
			wait1Msec(500);
			moveRobotBR(30,0.75);
			wait1Msec(500);
			gyroTurn(false,30,135);
			wait1Msec(500);
			moveRobotBR(50,4);
		}
		wait1Msec(500);
		while(true){wait1Msec(100);}
	}
	else
	{
		heading = 0;
		////Initializes Servos to initial values
		//initializeServos();
		////Lifts the lift slightly off of the ground
		//initializeLift();
		////Moves the servos slightly forward to make sure the ablls dont roll out
		//setServos(127);
		if(_dirAC == 5)
		{
			moveRobotBR(30,0.75);
			gyroTurn(true,30,180);
			liftCenter();
			moveRobotBR(-30,0.75);
			dumpCenter();
			lowerCenter();
			gyroTurn(false,30,90);
			moveRobotBR(30,1);
			gyroTurn(true,30,90);
			moveRobotBR(60,4);
		}
		else if(_dirAC > 1)
		{
			moveRobotBR(30,0.75);
			wait1Msec(500);
			gyroTurn(false,30,45);
			wait1Msec(500);
			moveRobotBR(50,4);
		}
		else
		{
			gyroTurn(true,30,45);
			wait1Msec(500);
			moveRobotBR(30,0.75);
			wait1Msec(500);
			gyroTurn(false,30,135);
			wait1Msec(500);
			moveRobotBR(50,4);
		}
	}
}
