#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogInactive)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeftPulley, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorRightPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servoLeftBridge,      tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool ramp = true;
bool FLdone = false;
bool BLdone = false;
bool FRdone = false;
bool BRdone = false;
int _dirAC = 0;
int _dirDC = 0;
int irTotal = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5, acS1, acS2, acS3, acS4, acS5 = 0;
int heading = 0;

#include "reset.h"
#include "JoystickDriver.c"
#include "autonomousChooserNew.h"
#include "moveRobotRearW.h"
#include "setServos.h"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
#include "gyroTurn.h"
#include "lift.h"
#include "readIR.h"

void initializeRobot()
{

}

task main()
{
	initializeRobot();
	//TESTING
	//TESTING
	//TESTING
	gyroTurn(false,30,90);
	while(true){wait1Msec(100);}
	//^^^TESTING
	disableDiagnosticsDisplay();
	startTask(autonomousChooserSimple);
	//while(true){wait1Msec(100);}
	waitForStart();
	stopTask(autonomousChooserSimple);
	if(ramp)
	{
		heading = 180;
		//Initializes Servos to initial values
		initializeServos();
		//Lifts the lift slightly off of the ground
		initializeLift();
		////Moves the servos slightly forward to make sure the ablls dont roll out
		setServos(127);
		wait1Msec(1000);
		//Moves the robot near the medium tube
		moveRobotBRamp(-20, 2.4); //Move down the ramp
		moveRobotBR(-20,1); //Move back more
		lift60(); //Lift the balls to the tube
		moveRobotBR(-15,0.5); //Slightly adjust the robot
		setServos(100); //Drop the balls
		setServos(255); //Raise the lift back up
		moveRobotBR(15,0.5); //Move robot back forward
		lower60(); //Lower the lift
		moveRobotBR(-20,0.5); //Move robot back more
		gyroTurn(false,30,90); //Turn to the right 90 degrees
		//Now you should be facing the center structure
		moveRobotBR(30,1); //Move forward for better readings
		irTotal = readIR(); //Read the IR value
		if(_dirAC == 5) //If preset 1
		{
			gyroTurn(true,30,45); //Turn left 45 degrees
			moveRobotBR(30,0.75); //Go forward
			gyroTurn(false,30,45); //Turn right 45 degrees
			moveRobotBR(60,4); //Run into the kickstand
		}
		else if(_dirAC > 1) //If preset 2
		{
			moveRobotBR(30,0.75); //Move forward a bit
			gyroTurn(true,30,45); //Turn 45 degrees to the left
			moveRobotBR(60,4); //Run into the kickstand
		}
		else //If preset 3
		{
			gyroTurn(true,30,45); //Turn 45 degrees left
			moveRobotBR(30,1.25); //Move forward
			gyroTurn(false,30,45); //Rotate 45 degrees to the right
			gyroTurn(false,30,90); //Rotate 90 degrees to the right
			moveRobotBR(60,4); //Run into the kickstand
		}
		while(true){wait1Msec(100);}
	}
	else
	{
		heading = 0;
		//Initializes Servos to initial values
		initializeServos();
		//Lifts the lift slightly off of the ground
		initializeLift();
		//Moves the servos slightly forward to make sure the ablls dont roll out
		setServos(127);
		wait1Msec(1000);
		moveRobotBR(30,1); //Move robot forward for better IR readings
		if(_dirAC == 5) //If preset 3
		{
			moveRobotBR(30,0.75); //Move forward
			gyroTurn(true,30,180); //Rotate 180 degrees
			liftCenter(); //Lift to the center
			moveRobotBR(-30,0.75); //Move back to adjust
			dumpCenter(); //Dump the balls into the goal, and return the servos to a position so that the lift can be lowered
			lowerCenter(); //Lower the lift
			gyroTurn(false,30,90); //Turn to the right 90 degrees
			moveRobotBR(30,1); //Move forward
			gyroTurn(true,30,90); //Turn to the left 90 degrees
			moveRobotBR(60,4); //Run into kickstand
		}
		else if(_dirAC > 1) //If preset 2
		{
			moveRobotBR(30,0.75); //Move forward
			gyroTurn(true,30,45); //Turn 45 degrees to the left
			moveRobotBR(30,0.75); //Move the robot forward
			gyroTurn(false,30,45); //Turn 45 degrees to the right (should be facing center goal)
			gyroTurn(false,30,180); //Rotate 180 degrees so you can place ball in center goal
			moveRobotBR(-30,1); //Move back a bit
			liftCenter(); //Raise the lift
			moveRobotBR(-30,0.75); //Move drawbridge over the center goal
			dumpCenter(); //Dump the balls
			lowerCenter(); //Lower the lift
			gyroTurn(false,30,90); //Turn to the right 90 degrees
			moveRobotBR(30,1); //Move forward
			gyroTurn(true,30,90); //Turn to the left 90 degrees
			moveRobotBR(60,4); //Run into kickstand
		}
		else //If preset 1
		{
			gyroTurn(true,30,45); //Turn to the left 45 degrees
			moveRobotBR(30,2.5); //Go forward
			gyroTurn(true,30,45); //Turn to the left 45 degrees
			moveRobotBR(-30,1.5); //Move backwards to get closer to center goal
			liftCenter(); //Raise the lift
			moveRobotBR(-30,0.75); //Adjust back to the center goal
			dumpCenter(); //Dump the balls
			lowerCenter(); //Lower the lift
			gyroTurn(false,30,90); //Turn to the right 90 degrees
			moveRobotBR(30,1); //Move forward
			gyroTurn(true,30,90); //Turn to the left 90 degrees
			moveRobotBR(60,4); //Run into kickstand
		}
	}
}
