#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     BR,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task drive(){

motor[FL] = 100;
motor[FR] = 100;
motor[BL] = 100;
motor[BR] = 100;

}

task main()
{

	startTask(drive);
	while(true){}
}
