#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     Sensor,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Ramp
	motor[motorFL] = -60;
	motor[motorBL] = -60;
	motor[motorFR] = 60;
	motor[motorBR] = 60;
	wait1Msec(2000);
	// Rolling goal
	motor[motorFL] = 60;
	motor[motorBL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = -60;
	wait1Msec(2250);
	// Infront of parking zone
	motor[motorFL] = 60;
	motor[motorBL] = 60;
	motor[motorFR] = -60;
	motor[motorBR] = -60;
	wait1Msec(1200);
	// Move back into parking zone
	motor[motorFL] = 30;
	motor[motorBL] = -30;
	motor[motorFR] = 30;
	motor[motorBR] = -30;
	wait1Msec(500);
	motor[motorFL] = 0;
	motor[motorBL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = 0;

}
