#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     Sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{

  return;
}

;

task ultsense (){
	short ultsonar = 0;

while(true){
ultsonar = SensorRaw[Sonar];
while (ultsonar > 20){
	motor[motorFL] = -50;
	motor[motorBL] = -50;
	motor[motorFR] = 50;
	motor[motorBR] = 50;
}
	motor[motorFL] = 0;
	motor[motorBL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = 0;
wait1Msec(2);
}
}

task main()
{
  initializeRobot();

  waitForStart();
	startTask(ultsense);
  while (true)
  {
  	wait1Msec(10);
  }

}
