#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogInactive)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeftPulleyT, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLeftPulley, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorRightPulley, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servoLeftBridge,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoRightBridge,     tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoRearGrabberR,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servoRearGrabberL,    tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servo1,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Establishing global variables
float x1 = 0;
float y1 = 0;
float x2 = 0;
float joy2y1 = 0;
float joy2y2 = 0;
float num = 0.00;
float FL = 0.00;
float BL = 0.00;
float FR = 0.00;
float BR = 0.00;
int y2 = 0;
int liftServoPos = 0;
bool autoLiftRunning = false;
bool stabilizing = false;
bool forceStopped = false;
int stabilizingVal = 0;
int liftStick = 0;

#include "JoystickDriver.c"
#include "normalize.h"

void initializeRobot()
{
	nMotorEncoder[motorRightPulley] = 0;
	return;
} // end of initialization

/*bool isJoy2AFK()
{
	getJoystickSettings(joystick);
	int stick1 = joystick.joy2_y1;
	int stick2 = joystick.joy2_y2;
	if(!joy2Btn(1) && !joy2Btn(2) && !joy2Btn(3) && !joy2Btn(4) && !joy2Btn(5) && !joy2Btn(6) && !joy2Btn(7) && !joy2Btn(8) && stick1 < 10 && stick2 < 10)
		return true;
	else
		return false;
}*/

/*bool autoLiftStopped(bool thing)
{
	getJoystickSettings(joystick);
	int liftStick = joystick.joy2_y1;
	if(thing)
		return true;
	if(!joy1Btn(1) && !joy2Btn(6) && !joy2Btn(8) && liftStick < 10)
		return true;
	return false;
}

void dumpIt(int motorEncoderHeight)
{
	int time = motorEncoderHeight / 2;
	int startVal = nMotorEncoder[motorRightPulley];
	bool stopped = false;
	int dif = 0
	clearTimer(T3);
	while(!stopped && nMotorEncoder[motorRightPulley] < motorEncoderHeight && time1(T3) < time)
	{
		motor[motorRightPulley] = 100;
		motor[motorLeftPulley] = 100;
		stopped = autoLiftStopped(stopped);
		wait1Msec(20);
	}
	if(!stopped)
	{
		motor[motorRightPulley] = 30;
		motor[motorLeftPulley] = 30;
		servo[servoLeftBridge] = 240;
		servo[servoRightBridge] = 0;
		while(!stopped && dif < 125)
		{
			dif = dif + 5;
			servo[servoLeftBridge] = 240 - dif;
			servo[servoRightBridge] = dif;
			stopped = autoLiftStopped(stopped);
			wait1Msec(75);
		}
	}
	if(!stopped)
	{
		wait1Msec(750);
		while(!stopped && dif > 0)
		{
			dif = dif - 5;
			servo[servoLeftBridge] = 240 - dif;
			servo[servoRightBridge] = dif;
			stopped = autoLiftStopped(stopped);
			wait1Msec(25);
		}
	}
	if(!stopped)
	{
		while(!stopped && nMotorEncoder[motorRightPulley] > 1500 && time1(T3) < time)
		{
			motor[motorRightPulley] = -100;
			motor[motorLeftPulley] = -100;
			stopped = autoLiftStopped(stopped);
			wait1Msec(20);
		}
	}
	motor[motorRightPulley] = 0;
	motor[motorLeftPulley] = 0;
	wait1Msec(20);
}

task autoLift()
{
	while(true)
	{
		getJoystickSettings(joystick);
		int liftStick = joystick.joy2_y1;
		if(joy2Btn(2))
		{
			dumpIt(11500);
			wait1Msec(100);
		}
		else if(joy2Btn(3))
		{
			dumpIt(8000);
			wait1Msec(100);
		}
		else if(joy2Btn(4))
		{
			dumpIt(5000);
			wait1Msec(100);
		}
		else if(joy2Btn(1))
		{
			int stabilizingVal = abs(nMotorEncoder[motorRightPulley]);
			wait1Msec(500);
			while(isJoy2AFK())
			{
				liftStick = joystick.joy2_y1;
				int change = stabilizingVal - abs(nMotorEncoder[motorRightPulley]);
				if(change > 100)
				{
					motor[motorRightPulley] = 30;
					motor[motorLeftPulley] = 30;
				}
				else
				{
					motor[motorRightPulley] = 0;
					motor[motorLeftPulley] = 0;
				}
				wait1Msec(20);
			}
		}
		else if(isJoy2AFK())
		{
			int stabilizingVal = abs(nMotorEncoder[motorRightPulley]);
			clearTimer(T4);
			while(isJoy2AFK() && time1(T4) < 5000)
			{
				liftStick = joystick.joy2_y1;
				int change = stabilizingVal - abs(nMotorEncoder[motorRightPulley]);
				if(change > 100)
				{
					motor[motorRightPulley] = 30;
					motor[motorLeftPulley] = 30;
				}
				else
				{
					motor[motorRightPulley] = 0;
					motor[motorLeftPulley] = 0;
				}
				wait1Msec(20);
			}
		}
		else
		{
			motor[motorRightPulley] = 0;
			motor[motorLeftPulley] = 0;
		}
		//wait1MSec(10);
	}
}*/
void drop()
{
	autoLiftRunning = true;
	if(autoLiftRunning)
	{
		motor[motorRightPulley] = 30;
		motor[motorLeftPulley] = 30;
		liftServoPos = 25;
		//nxtDisplayCenteredBigTextLine(5,"%d",liftServoPos);
		wait1Msec(15);
		while(autoLiftRunning && liftServoPos < 125)
		{
			liftServoPos += 5;
			/*servo[servoRightBridge] = liftServoPos;
			servo[servoLeftBridge] = 240 - liftServoPos;*/
			//nxtDisplayCenteredBigTextLine(5,"%d",liftServoPos);
			wait1Msec(75);
		}
	}
	int count = 0;
	while(autoLiftRunning && count < 40)
	{
		count++;
		wait1Msec(49);
	}
	while(autoLiftRunning && liftServoPos > 0)
	{
		liftServoPos -= 5;
		/*servo[servoRightBridge] = liftServoPos;
		servo[servoLeftBridge] = 240 - liftServoPos;*/
		//nxtDisplayCenteredBigTextLine(5,"%d",liftServoPos);
		wait1Msec(25);
	}
}

task isAutoLiftRunning() //Checks if autoLift is interrupted. Also controls lift servo movement
{
	while(true)
	{
		nxtDisplayCenteredBigTextLine(2,"%d",nMotorEncoder[motorRightPulley]);
		if(autoLiftRunning)
			//nxtDisplayCenteredBigTextLine(2,"true");
		else
			//nxtDisplayCenteredBigTextLine(2,"false");
		if(liftServoPos > 140)
			liftServoPos = 140;
		else if(liftServoPos < 0)
			liftServoPos = 0;
		//if(!autoLiftRunning)
		//{
			servo[servoRightBridge] = liftServoPos;
			servo[servoLeftBridge] = 240 - liftServoPos;
		//}
		if(abs(joy2y1) > 10 || joy2Btn(1))
		{
			forceStopped = true;
			autoLiftRunning = false;
		}
		wait1Msec(25);
	}
}

void autoLift(int autoLiftDist)
{
	bool finishedAll = false;
	autoLiftRunning = true;
	int time = autoLiftDist / 2;
	int startVal = nMotorEncoder[motorRightPulley];
	liftServoPos = 25;
	int temp = startVal + autoLiftDist;
	int change = 0;
	clearTimer(T3);
	if(autoLiftRunning)
	{
		while(autoLiftRunning && nMotorEncoder[motorRightPulley] < temp && time1(T3) < time)
		{
			motor[motorRightPulley] = 100;
			motor[motorLeftPulley] = 100;
			//startVal
			wait1Msec(20);
		}
	}
	if(autoLiftRunning)
	{
		motor[motorRightPulley] = 30;
		motor[motorLeftPulley] = 30;
		liftServoPos = 25;
		//nxtDisplayCenteredBigTextLine(5,"%d",liftServoPos);
		wait1Msec(15);
		while(autoLiftRunning && liftServoPos < 125)
		{
			liftServoPos += 5;
			/*servo[servoRightBridge] = liftServoPos;
			servo[servoLeftBridge] = 240 - liftServoPos;*/
			//nxtDisplayCenteredBigTextLine(5,"%d",liftServoPos);
			wait1Msec(75);
		}
	}
	int count = 0;
	while(autoLiftRunning && count < 40)
	{
		count++;
		wait1Msec(49);
	}
	while(autoLiftRunning && liftServoPos > 0)
	{
		liftServoPos -= 5;
		/*servo[servoRightBridge] = liftServoPos;
		servo[servoLeftBridge] = 240 - liftServoPos;*/
		//nxtDisplayCenteredBigTextLine(5,"%d",liftServoPos);
		wait1Msec(25);
	}
	clearTimer(T3);
	while(autoLiftRunning && nMotorEncoder[motorRightPulley] > startVal + 1000 && time1(T3) < time)
	{
		motor[motorRightPulley] = -100;
		motor[motorLeftPulley] = -100;
		wait1Msec(20);
	}
	if(autoLiftRunning)
		finishedAll = true;
	if(forceStopped || finishedAll)
	{
		motor[motorRightPulley] = 0;
		motor[motorLeftPulley] = 0;
	}
	wait1Msec(20);
	autoLiftRunning = false;
}

task moveLift()
{
	while(true)
	{
		//Debugging code
		if(liftServoPos > 140) //Makes sure liftServoPos doesn't go above 140
			liftServoPos = 140;
		if(liftServoPos < 0) //Makes sure liftServPos doesn't go below 0
			liftServoPos = 0;
		if(abs(joy2y1) > 10) //If the liftStick is being used
		{
			stabilizing = false;
			motor[motorRightPulley] = joy2y1;
			motor[motorLeftPulley] = joy2y1;
			wait1Msec(35);
		}
		if(joy2Btn(6)) //Moves the lift servos down if Joy2 Top Right Trigger is pressed
		{
			stabilizing = false;
			liftServoPos -= 2;
			wait1Msec(8);
		}
		else if(joy2Btn(8)) //Moves the lift servos up if Joy2 Bottom Right Trigger is pressed
		{
			stabilizing = false;
			liftServoPos += 2;
			wait1Msec(8);
		}
		else if(joy2Btn(1)) //If the "X" button is pressed(joy2Btn1), run autoLift for the medium goal
		{
			stabilizing = false;
			autoLift(5050);
			wait1Msec(5);
		}
		else if(joy2Btn(2))
		{
			stabilizing = false;
			drop();
			wait1Msec(5);
		}
		else if(joy2Btn(3)) //If the "B" button is pressed(joy2Btn3), run autoLift for the tall goal
		{
			stabilizing = false;
			autoLift(7150);
			wait1Msec(5);
		}
		else if(joy2Btn(4)) //If the "Y" button is pressed(joy2Btn3), run center for the center goal
		{
			stabilizing = false;
			autoLift(11500);
			wait1Msec(5);
		}
		else if(abs(joy2y1) < 10) //Auto lift is not running and no buttons are being pressed
		{
			motor[motorRightPulley] = 0;
			motor[motorLeftPulley] = 0;
			if(!stabilizing)
			{
				stabilizingVal = abs(nMotorEncoder[motorRightPulley]);
				clearTimer(T4);
			}
			stabilizing = true;
			if(time1(T4) < 5000 && abs(nMotorEncoder[motorRightPulley]) > 1500)
			{
				int change = stabilizingVal - abs(nMotorEncoder[motorRightPulley]);
				if(change > 100)
				{
					motor[motorRightPulley] = 30;
					motor[motorLeftPulley] = 30;
				}
				else
				{
					motor[motorRightPulley] = 0;
					motor[motorLeftPulley] = 0;
				}
			}
			else
			{
				motor[motorRightPulley] = 0;
				motor[motorLeftPulley] = 0;
			}
			wait1Msec(20);
		}
		wait1Msec(15);
	}
	/*bool grabChoice = true;
	if(grabChoice)
	{
		int diff = 0;
		servo[servoRightBridge] = 0;
		servo[servoLeftBridge] = 240;
		while(true)
		{
			if(joy2Btn(6))
			{
				diff += 1;
				if(diff < 0)
					diff = 0;
				else if(diff > 140)
					diff = 140;
				servo[servoRightBridge] = diff;
				servo[servoLeftBridge] = 240 - diff;
			}
			else if(joy2Btn(8))
			{
				diff -= 2;
				if(diff < 0)
					diff = 0;
				else if(diff > 140)
					diff = 140;
				servo[servoRightBridge] = diff;
				servo[servoLeftBridge] = 240 - diff;
			}
			wait1Msec(20);
			nxtDisplayCenteredBigTextLine(2,"%d",diff);
		}
	}
	else
	{
		int diff = 0;
		servo[servoRightBridge] = 0;
		servo[servoLeftBridge] = 240;
		while(true)
		{
			int stickMove = joystick.joy2_y2;
			if(stickMove > 20)
				diff += 1;
			else if(stickMove < -20)
				diff -= 1;
			if(diff < 0)
				diff = 0;
			else if(diff > 140)
				diff = 140;
			servo[servoRightBridge] = diff;
			servo[servoLeftBridge] = 240 - diff;
			wait1Msec(5);
			//nxtDisplayCenteredBigTextLine(2,"%d",diff);
		}
	}*/
	while(true){wait1Msec(20);}
}

task moveGrabber()
{
	bool grabChoice = false; //True for
	if(grabChoice)
	{
		int dif = 127;
		while(true)
		{
			if(joy1Btn(6))
				dif+=10;
			if(joy1Btn(8))
				dif-=10;
			if(dif < 0)
				dif = 0;
			if(dif > 270)
				dif = 270;
			servo[servoRearGrabberR] = dif - 15;
			servo[servoRearGrabberL] = 255 - dif;
			//nxtDisplayCenteredBigTextLine(2,"%d",dif);
			wait1Msec(50);
		}
	}
	else
	{
		int dif = 127;
		while(true)
		{
			if(joy1Btn(6))
				dif=187;
			if(joy1Btn(8))
				dif=50;
			servo[servoRearGrabberR] = dif - 15;
			servo[servoRearGrabberL] = 255 - dif;
			wait1Msec(50);
		}
	}
}

/*task raiseLift()
{
	while(true)
	{
		getJoystickSettings(joystick);
		int liftStick = joystick.joy2_y1;
		if(abs(liftStick) >= 10)
		{
			motor[motorLeftPulley] = liftStick;
			motor[motorRightPulley] = liftStick;
		}
	}
	while(true){wait1Msec(50);}
}*/

task HoloDrive()
{
	getJoystickSettings(joystick);
	startTask(isAutoLiftRunning,10);
	startTask(moveLift); //Starts the task for moving the lift servos
	startTask(moveGrabber); //Start the task for moving the rear grabbers
	//startTask(raiseLift); //Starts the task for moving the lift up and down
	//startTask(autoLift); //Starts the task for automatically moving the lift to the goals
	while(true)
	{
		//Takes input from the joystick and sets variables to them
		getJoystickSettings(joystick);
		x1 = joystick.joy1_x1;
		y1 = joystick.joy1_y1;
		x2 = joystick.joy1_x2;
		y2 = joystick.joy1_y2;
		joy2y1 = joystick.joy2_y1;
		joy2y2 = joystick.joy2_y2;

		//Scales all the values to the 0-100 range of motor controllers
		x1 = x1 / 1.28;
		y1 = y1 / 1.28;
		x2 = x2 / 1.28;
		y2 = y2 / 1.28;
		joy2y1 = joy2y1 / 1.28;
		joy2y2 = joy2y2 / 1.28;

		//Formula for determining the wheel speeds based on the joystick position.
		FL = y1 + x1 + x2;
		BL = y1 - x1 + x2;
		FR = y1 - x1 - x2;
		BR = y1 + x1 - x2;

		normalize(); //Use normalize function to compensate for wheel values above 100 or below -100

		//Scaling motor values
		if(abs(x1) > 10 && abs(y1) > 10) //If the robot is strafing, run the wheels at full speed
		{
			FL = FL;
			BL = BL;
			FR = FR;
			BR = BR;
		}
		else if(joy1Btn(5)) //If the driver is pressing the speed up button, run at full speed
		{
			FL = FL;
			BL = BL;
			FR = FR;
			BR = BR;
		}
		else //Otherwise, run at 60% speed
		{
			FL = FL * 0.60;
			BL = BL * 0.60;
			FR = FR * 0.60;
			BR = BR * 0.60;
		}

		//Run the motors
		//This section checks
		if((abs(x2) >= 10) && (joy1Btn(3))) //Slow down button 1
		{
			motor[motorFL] = x2 / 5;
			motor[motorBL] = x2 / 5;
			motor[motorFR] = x2 / 5;
			motor[motorBR] = x2 / 5;
		}
		else if((abs(x2) >= 10) && (joy1Btn(2))) //Slower down button 2
		{
			motor[motorFL] = x2 / 3;
			motor[motorBL] = x2 / 3;
			motor[motorFR] = x2 / 3;
			motor[motorBR] = x2 / 3;
		}
		else if(abs(x2) >= 10) //Regular running speed
		{
			motor[motorFL] = x2;
			motor[motorBL] = x2;
			motor[motorFR] = x2;
			motor[motorBR] = x2;
		}
		else if((abs(x1) >= 10 || abs(y1) >= 10) && joy1Btn(2))
		{
			motor[motorFL] = FL / 2;
			motor[motorBL] = BL / 2;
			motor[motorFR] = -FR / 2;
			motor[motorBR] = -BR / 2;
		}
		else if((abs(x1) >= 10 || abs(y1) >= 10) && joy1Btn(3))
		{
			motor[motorFL] = FL / 3;
			motor[motorBL] = BL / 3;
			motor[motorFR] = -FR / 3;
			motor[motorBR] = -BR / 3;
		}
		else if(abs(x1) >= 10 || abs(y1) >= 10)
		{
			motor[motorFL] = FL;
			motor[motorBL] = BL;
			motor[motorFR] = -FR;
			motor[motorBR] = -BR;
		}
		else
		{
			motor[motorFL] = 0;
			motor[motorBL] = 0;
			motor[motorFR] = 0;
			motor[motorBR] = 0;
		}
		//Spins manipulator
		if(joy1Btn(5))
			motor[motorManipulator] = -70;
		else if(joy1Btn(7))
			motor[motorManipulator] = 70;
		else
			motor[motorManipulator] = 0;
		wait1Msec(5);
	}
}

task main()
{
	initializeRobot();
	waitForStart();
	getJoystickSettings(joystick);
	//startTask(moveGrabber);
	//startTask(raiseLift);
	startTask(HoloDrive);
	while(true){wait1Msec(5);}
} // End of task main
