#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     Gyro,           sensorAnalog)
#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     Ultrasonic,     sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorManipulator, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorNull,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorIFR,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers\hitechnic-sensormux.h"
#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-gyro.h"
//WIP DO NOT TOUCH. OR LOOK.
int _dirDC = 0;
int _dirAC = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;
int irNear = 0;
int irFar = 0;
int irDist = 0;
int irTotal = 0;
int preset = 0;
int num = 0;
int ramp = 0;
int red = 0;
int blue = 0;
int irMax = 0;

float ultsonar = 0.0;
int irTotalOld = 0;
int alignDir = 20;
int final = 0;
int count = 1;

	_dirDC = HTIRS2readDCDir(HTIRS2);
	_dirAC = HTIRS2readACDir(HTIRS2);
	HTIRS2readAllDCStrength(HTIRS2, dcS1, dcS2, dcS3, dcS4, dcS5);
	HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5);
	irFar = acS3;
	irNear = dcS3;



//Starting from ParkingZone; Center goal at position 1
task parkingZone1()
{
	if (irDist == 0)
	{
		//Move diagonally until the robot is next to center goal
		if(abs(nMotorEncoder[motorFL]) < 840 && abs(nMotorEncoder[motorBR] < 840){
				motor[motorFL] = 100;
				motor[motorBL] = 0;
				motor[motorFR] = 0;
				motor[motorBR] = 100;
		}
		nMotorEncoder[motorFL] = 0;
		nMotorEncoder[motorBR] = 0;
		//Rotate the robot so the back is facing the center goal
		if (abs(nMotorEncoder[motorFL]) > -560 && abs(nMotorEncoder[motorBR] < 560 && abs(nMotorEncoder[motorBL] > -560 && abs(nMotorEncoder[motorFR] < 560)
		{
				motor[motorFL] = -100;
				motor[motorBL] = 100;
				motor[motorFR] = 100;
				motor[motorBR] = -100;
		}
		//Lift the funnel
		//Rotate funnels downwards
		//Open funnel to drop off ball (? baseball)
		//Lower lift
		nMotorEncoder[motorFL] = 0;
		nMotorEncoder[motorBL] = 0;
		nMotorEncoder[motorFR] = 0;
		nMotorEncoder[motorBR] = 0;
		//Strafe right
		if (abs(nMotorEncoder[motorFL]) < 560 && abs(nMotorEncoder[motorBR] < 560 && abs(nMotorEncoder[motorBL] > -560 && abs(nMotorEncoder[motorFR] > -560)
		{
				motor[motorFL] = 100;
				motor[motorBL] = -100;
				motor[motorFR] = -100;
				motor[motorBR] = 100;
		}
		nMotorEncoder[motorFL] = 0;
		nMotorEncoder[motorBL] = 0;
		nMotorEncoder[motorFR] = 0;
		nMotorEncoder[motorBR] = 0;
		if (abs(nMotorEncoder[motorFL]) < 560 && abs(nMotorEncoder[motorBR] < 560 && abs(nMotorEncoder[motorBL] < 560 && abs(nMotorEncoder[motorFR] < 560){}

	}
}



task main()
{
	initializeRobot();
	//waitForStart();
}
